sudo: required
dist: trusty
language: clojure
git:
    submodules: false
before_install:
    - sudo apt-add-repository ppa:ubuntugis/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install libgdal-dev libgdal-java -y
    # - curl --location --silent -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -
    # - sudo apt-get install -y -qq dsc21
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
script:
  - make db-setup
  - make check
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - /^topic/
notifications:
  email:
      # the following won't work until the Travis
      # but here is sorted:
      # https://github.com/travis-ci/travis-ci/issues/2513
      - lcmap-dev-notifications@googlegroups.com
      - duncan.mcgreggor.ctr@usgs.gov
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#data
