FROM usgseros/ubuntu-gis-clj:0.5.0
MAINTAINER USGS LCMAP http://eros.usgs.gov
LABEL Description="This image is used to initialize the LCMAP DB schema and ingest ARD"

VOLUME ["/root/.usgs","/data"]
COPY app.jar app.jar
